/*
 * megadotnet 使用Swagger2 构建RESTful API
 * megadotnet  https://github.com/megadotnet/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.LoginVM;
import io.swagger.client.model.ResponseEntity;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserJwtControllerApi
 */
@Ignore
public class UserJwtControllerApiTest {

    private final UserJwtControllerApi api = new UserJwtControllerApi();

    
    /**
     * authorize
     *
     * authorize
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorizeUsingPOSTTest() throws ApiException {
        LoginVM loginVM = new LoginVM();
        loginVM.setPassword("admin");
        loginVM.setUsername("admin");
        loginVM.setRememberMe(true);
        ApiResponse<ResponseEntity> response = api.authorizeUsingPOSTWithHttpInfo(loginVM);
        Assert.assertNotNull(response);
        String jwtTokenForTest = response.getHeaders().get("Authorization").get(0);
        Assert.assertNotNull(jwtTokenForTest);
    }
    
}
