/*
 * megadotnet 使用Swagger2 构建RESTful API
 * megadotnet  https://github.com/megadotnet/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.KeyAndPasswordVM;
import io.swagger.client.model.ManagedUserVM;
import io.swagger.client.model.ResponseEntity;
import io.swagger.client.model.UserDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserAccountControllerApi
 */
@Ignore
public class UserAccountControllerApiTest {

    private final UserAccountControllerApi api = new UserAccountControllerApi();

    
    /**
     * activateAccount
     *
     * activate Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void activateAccountUsingGETTest() throws ApiException {
        String key = null;
        String response = api.activateAccountUsingGET(key);

        // TODO: test validations
    }
    
    /**
     * changePassword
     *
     * change Password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changePasswordUsingPOSTTest() throws ApiException {
        String password = null;
        ResponseEntity response = api.changePasswordUsingPOST(password);

        // TODO: test validations
    }
    
    /**
     * finishPasswordReset
     *
     * finish PasswordReset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void finishPasswordResetUsingPOSTTest() throws ApiException {
        KeyAndPasswordVM keyAndPassword = null;
        String response = api.finishPasswordResetUsingPOST(keyAndPassword);

        // TODO: test validations
    }
    
    /**
     * getAccount
     *
     * get Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountUsingGETTest() throws ApiException {
        UserDTO response = api.getAccountUsingGET();

        // TODO: test validations
    }
    
    /**
     * isAuthenticated
     *
     * is Authenticated
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isAuthenticatedUsingGETTest() throws ApiException {
        String response = api.isAuthenticatedUsingGET();

        // TODO: test validations
    }
    
    /**
     * registerAccount
     *
     * register Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerAccountUsingPOSTTest() throws ApiException {
        ManagedUserVM managedUserVM = null;
        ResponseEntity response = api.registerAccountUsingPOST(managedUserVM);

        // TODO: test validations
    }
    
    /**
     * requestPasswordReset
     *
     * request PasswordReset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestPasswordResetUsingPOSTTest() throws ApiException {
        String mail = null;
        ResponseEntity response = api.requestPasswordResetUsingPOST(mail);

        // TODO: test validations
    }
    
    /**
     * saveAccount
     *
     * save Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveAccountUsingPOSTTest() throws ApiException {
        UserDTO userDTO = null;
        ResponseEntity response = api.saveAccountUsingPOST(userDTO);

        // TODO: test validations
    }
    
}
